;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-delete-forward
	c-electric-lt-gt
	c-electric-semi&comma
	c-electric-slash
	kill-region
	autopair-insert-opening
	autopair-newline
	beginning-of-buffer
	))

(setq mc/cmds-to-run-once
      '(
	))
