;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				autopair-insert-opening
				autopair-insert-or-skip-quote
				autopair-newline
				autopair-skip-close-maybe
				beginning-of-buffer
				c-beginning-of-statement
				c-electric-brace
				c-electric-colon
				c-electric-delete-forward
				c-electric-lt-gt
				c-electric-semi&comma
				c-electric-slash
				c-electric-star
				c-indent-line-or-region
				dabbrev-expand
				delete-horizontal-space
				electric-newline-and-maybe-indent
				indent-for-tab-command
				kill-region
				org-beginning-of-line
				org-cycle
				org-delete-char
				org-end-of-line
				org-force-self-insert
				org-kill-line
				org-self-insert-command
				org-yank
				uncomment-region
				yank-and-indent
				))

(setq mc/cmds-to-run-once
      '(
				company-complete
				info-emacs-manual
				org-edit-src-save
				))
